//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by upgrader.rc
//
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDR_UPGRADTYPE                  129
#define IDS_ERR_WINSOCK                 129
#define IDS_ERR_SOCK_OPENFAIL           130
#define IDB_ROUTER                      131
#define IDS_ERR_SEND                    131
#define IDD_TFTP_PROGESS                132
#define IDS_ERR_RECV                    132
#define IDD_ADMIN_PASSWORD              133
#define IDS_ERR_PASSWORD                133
#define IDS_FIRMWARE_UPGRADE_COMPLETE   134
#define IDS_ERR_OPENFILE                135
#define IDD_SEARCH_WAIT                 135
#define IDS_ERR_FILENAME                136
#define IDS_ERR_UPGRADE                 137
#define IDS_SEARCH                      138
#define IDD_UPGRADE_MANUAL              139
#define IDS_UPGRADE_AUTO                139
#define IDD_DEVICE_INFO                 140
#define IDS_UPGRADE_MANUAL              140
#define IDR_SEARCH_AVI                  141
#define IDS_DEVICE_INFO                 141
#define IDS_CONN_WEB                    142
#define IDS_PROPSHT_CAPTION             143
#define IDB_SWITCH                      144
#define IDS_REBOOT                      144
#define IDB_GATEWAY                     145
#define IDD_IP_CONFIG                   146
#define IDD_LOGIN                       149
#define IDD_WAIT_RESET                  150
#define IDD_WLAN_SETTING                151
#define IDD_WIZARD_LOGIN                163
#define IDD_WIZARD_SYSTEM               164
#define IDD_WIZARD_SECURITY             166
#define IDD_WIZARD_IP_CONFIG            167
#define IDD_WIZARD_SYSTEM_AP            169
#define IDD_WIZARD_SYSTEM_CLIENTINF     171
#define IDD_WIZARD_SYSTEM_REPEATER      172
#define IDD_WIZARD_SECURITY_REPEATER    175
#define IDD_WIZARD_ENC_WEP              176
#define IDD_WIZARD_ENC_WPAPSK           177
#define IDD_WIZARD_FINAL                178
#define IDD_WIZARD_SYSTEM_CLIENT        180
#define IDD_WIZARD_SYSTEM_CLIENTADHOC   181
#define IDD_WIZARD_SYSTEM_DECNAME       183
#define IDD_WIZARD_SUMMARY              185
#define IDB_HEADER                      187
#define IDB_BG_OPMODE                   206
#define IDB_BG_WLAN_AP                  207
#define IDB_BG_WLAN_REP                 209
#define IDB_BG_WLAN_ADHOC               211
#define IDB_BG_NETWORK_MODE             212
#define IDB_BG_SECURITY2                214
#define IDB_BG_SECURITY1                215
#define IDB_BG_WEP                      216
#define IDB_BG_WPA_PSK                  217
#define IDB_BG_IP_SETTING               220
#define IDB_POINT                       221
#define IDB_BG_LOGIN                    222
#define IDB_BG_DEVICE_NAME              223
#define IDB_BG_OP_MODE                  224
#define IDB_BG_NETWORK                  225
#define IDB_BG_SEC_1                    230
#define IDB_BG_SEC_2                    231
#define IDB_BG_SUMMARY                  236
#define IDB_BG_CONFIRMATION             237
#define IDB_BG_S_LOGIN                  238
#define IDB_LOGIN                       240
#define IDB_IP_SETTING                  241
#define IDB_WIRELESS                    242
#define IDB_BG_INFO                     243
#define IDD_INTERFACE_SEL               246
#define IDD_WIZARD_ENC_WPA              247
#define IDD_WIZARD_ENCWPA               249
#define IDB_BG_WPA                      251
#define IDB_BG_ABOUT                    252
#define IDD_DIALOG_SEL_CONNECT          253
#define IDI_ICON_ADAPTER                255
#define IDD_DIALOG1                     256
#define IDD_HOST_CONFIG                 256
#define IDB_BITMAP1                     257
#define IDB_TOOLBAR                     257
#define IDC_PROGRESS                    1000
#define IDC_ADMIN_PASSWORD              1001
#define IDC_SEARCH_ANIMATE              1002
#define IDC_IPADDRESS                   1003
#define IDC_MANUAL_PASSWORD             1004
#define IDC_MANUAL_PATH                 1005
#define IDC_BROWSE_BUTTON               1006
#define IDC_MODEL_STATIC                1007
#define IDC_IPADDR_STATIC               1008
#define IDC_MACADDR_STATIC              1009
#define IDC_FWVER_STATIC                1010
#define IDC_STATIC_IP                   1011
#define IDC_WLAN_MACADDR_STATIC         1011
#define IDC_STATIC_MASK                 1012
#define IDC_STATIC_GATEWAY              1013
#define IDC_SUB_MASK                    1018
#define IDC_GATEWAY                     1019
#define IDC_DHCPENABLE                  1020
#define IDC_USERNAME                    1021
#define IDC_PASSWORD                    1022
#define IDC_PROGRESS_WAITING            1023
#define IDC_SSID                        1024
#define IDC_CHANNEL                     1025
#define IDC_SECURITY                    1026
#define IDC_ENCRYPTION                  1027
#define IDC_KEY                         1028
#define IDC_KEY_HEX                     1029
#define IDC_KEY_ASCII                   1030
#define IDC_STATIC_KEY1                 1031
#define IDC_STATIC_KEYINPUT             1032
#define IDC_STATIC_ENCRYPTION           1033
#define IDC_OP_MODE                     1034
#define IDC_KEY2                        1035
#define IDC_RADIO_DHCP_ENABLE           1036
#define IDC_RADIO3                      1037
#define IDC_WPAKEY                      1037
#define IDC_WIZARD_USERNAME             1039
#define IDC_WIZARD_PASSWORD             1040
#define IDC_WZSYS_NAME                  1041
#define IDC_WZOP_MODE                   1042
#define IDC_WZCHANNEL                   1043
#define IDC_WZSSID                      1044
#define IDC_WZRADIO_DHCP_ENABLE         1045
#define IDC_WZRADIO                     1046
#define IDC_WZIPADDRESS                 1047
#define IDC_WZSUB_MASK                  1048
#define IDC_WZGATEWAY                   1049
#define IDC_STATIC_WZKEY1               1053
#define IDC_WZKEY2                      1054
#define IDC_WZKEY1                      1055
#define IDC_WZKEY_ASCII                 1056
#define IDC_WZKEY_HEX                   1057
#define IDC_WZSECURITY                  1058
#define IDC_EDIT_WZKEY_ASCII            1058
#define IDC_WZENCRYPTION                1059
#define IDC_STATIC_WZENCRYPTION         1060
#define IDC_STATIC_WZKEYINPUT           1061
#define IDC_RADIO_WZCLIENT              1062
#define IDC_RADIO_WZREPEATER            1063
#define IDC_RADIO_WZAP                  1065
#define IDC_WZCHANNEL_AP                1066
#define IDC_WZSSID_AP                   1067
#define IDC_RADIO_STATIC_SSID           1069
#define IDC_WZSSID_CLIENT               1070
#define IDC_WZSSID_CLIENT_INF           1070
#define IDC_WZSSID_REPEATER             1071
#define IDC_WZCHANNEL_REPEATER          1072
#define IDC_WZWIRELESS_MODE_REPEATER    1072
#define IDC_RADIO_ANY_SSID              1074
#define IDC_RADIO_MODE_AP               1078
#define IDC_RADIO2                      1079
#define IDC_RADIO_MODE_CLIENT           1080
#define IDC_RADIO_WZAUTH                1081
#define IDC_RADIO4                      1082
#define IDC_RADIO5                      1083
#define IDC_RADIO_WZAUTH_REPEATER       1084
#define IDC_RADIO2_REPEATER             1085
#define IDC_RADIO3_REPEATER             1086
#define IDC_RADIO4_REPEATER             1087
#define IDC_RADIO_WZCHANGE_AUTH         1088
#define IDC_RADIO_AUTH                  1089
#define IDC_RADIO_AUTH_REPEATER         1090
#define IDC_RADIO_WZCHANGE_AUTH_REPEATER 1091
#define IDC_RADIO_WZKEY_ASCII           1092
#define IDC_RADIO_WZKEY_HEX             1093
#define IDC_EDIT_WZKEY_HEX              1094
#define IDC_STATIC_INPUT                1095
#define IDC_EDIT_WZKEY_WPAPSK           1096
#define IDC_COMBO_WZENCRYPTION          1097
#define IDC_RADIO_CLIENT_MODE           1098
#define IDC_RADIO2_CLIENT_MODE          1099
#define IDC_WZSSID_CLIENT_ADHOC         1100
#define IDC_WZCHANNEL_CLIENT_ADHOC      1101
#define IDC_WZWIRELESS_MODE_INF         1102
#define IDC_COMBO_WZWLAN_MODE           1103
#define IDC_EDIT_IPMASK_OLD             1104
#define IDC_EDIT_GATEWAY_OLD            1105
#define IDC_EDIT_IP_OLD                 1106
#define IDC_EDIT_IP_NEW                 1107
#define IDC_EDIT_GATEWAY_NEW            1109
#define IDC_EDIT_IPMASK_NEW             1110
#define IDC_EDIT_DEVNAME_OLD            1111
#define IDC_EDIT_DEVNAME_NEW            1112
#define IDC_RADIO1                      1112
#define IDC_EDIT_OPMODE_NEW             1113
#define IDC_CIPHER_TYPE                 1113
#define IDC_EDIT_OPMODE_OLD             1114
#define IDC_STATIC_TYPE                 1115
#define IDC_EDIT_WMODE_OLD              1116
#define IDC_COMBO_AUTH                  1116
#define IDC_EDIT_WMODE_NEW              1117
#define IDC_WIRELESS_MODE               1117
#define IDC_EDIT_CHANNEL_NEW            1118
#define IDC_STATIC_AUTH_WEP             1118
#define IDC_EDIT_CHANNEL_OLD            1119
#define IDC_MASK_STATIC                 1119
#define IDC_EDIT_ENCRYPT_OLD            1120
#define IDC_GATEWAY_STATIC              1120
#define IDC_EDIT_ENCRYPT_NEW            1121
#define IDC_DHCP_STATIC                 1121
#define IDC_EDIT_AUTH_NEW               1122
#define IDC_OPMODE_STATIC               1122
#define IDC_EDIT_AUTH_OLD               1123
#define IDC_WLANMODE_STATIC             1123
#define IDC_EDIT_SSID_OLD               1124
#define IDC_SSID_STATIC                 1124
#define IDC_EDIT_SSID_NEW               1125
#define IDC_CHANNEL_STATIC              1125
#define IDC_SECUTRITY_STATIC            1126
#define IDC_STATIC_AUTH                 1128
#define IDC_CONNECTSTATUS_STATIC        1128
#define IDC_STATIC_INPUT_TYPE           1129
#define IDC_BSSID_STATIC                1129
#define IDC_STATIC_BG                   1130
#define IDC_RSSI_STATIC                 1130
#define IDC_STATIC_BG_SUMMARY           1131
#define IDC_STATIC_S_LOGIN              1132
#define IDC_STATIC_LOGIN                1133
#define IDC_STATIC_BG_IP                1134
#define IDC_STATIC_BG_WLAN              1135
#define IDC_STATIC_BG_INFO              1136
#define IDC_COMBO_WZWLAN_MODE_ADHOC     1137
#define IDC_INTERFACE_SELECT            1138
#define IDC_STATIC_KEY_TYPE             1139
#define IDC_STATIC_NOTE                 1140
#define IDC_STATIC_NOTE_INF             1141
#define IDC_WZ_ADIUS_SERVER             1142
#define IDC_WZ_WPA_CIPHER               1143
#define IDC_EDIT_WZKEY_WPA              1144
#define IDC_ADIUS_SERVER                1146
#define IDC_IPADDRESS1                  1147
#define IDC_LIST_CONNECTION             1148
#define IDC_STATIC_DEFAULT_USER         1150
#define IDC_EDIT1                       1151
#define IDC_EDIT2                       1152
#define IDC_STATIC1                     1153
#define IDC_STATIC2                     1154
#define IDC_STATIC3                     1155
#define IDC_STATIC4                     1156
#define IDC_STATIC5                     1157
#define IDC_STATIC6                     1158
#define IDC_5GWLANMODE_STATIC           1159
#define IDC_5GSSID_STATIC               1160
#define IDC_5GRSSI_STATIC               1161
#define IDC_5GBSSID_STATIC              1162
#define IDC_5GCONNECTSTATUS_STATIC      1163
#define IDC_5GCHANNEL_STATIC            1164
#define IDC_5GSECUTRITY_STATIC          1165
#define IDC_2GWLANINFO_STATIC           1166
#define IDC_5GWLANINFO_STATIC           1167
#define IDC_5GWLAN_MACADDR_STATIC       1168
#define IDC_WLANOPMODE_STATIC           1169
#define IDC_5GWLANOPMODE_STATIC         1170
#define ID_SEARCH                       32771
#define ID_UPGRADE_AUTO                 32772
#define ID_UPGRADE_MANUAL               32773
#define ID_DEVICE_INFO                  32774
#define ID_CONFIG                       32775
#define ID_WEB                          32776
#define IDS_WIRELESS                    32777
#define ID_WIRELESS                     32778
#define ID_TOOLS_SELECTCONNECTION       32779
#define ID_WIZARD                       32780
#define ID_Menu                         32781
#define ID_REBOOT                       32782
#define IDS_TEXT_KEY_STRING64           61204
#define IDS_TEXT_KEY_STRING128          61205
#define IDS_TEXT_KEY_STRING152          61206
#define IDS_TEXT_KEY_HEX64              61207
#define IDS_TEXT_KEY_HEX128             61208
#define IDS_TEXT_KEY_HEX152             61209
#define IDS_TEXT_KEY_STR_PRESHARED      61210
#define IDS_TEXT_KEY_PSK                61211
#define IDS_TEXT_KEY_WEP                61212
#define IDS_DHCP_ENABLE                 61213
#define IDS_OPMODE_AP                   61214
#define IDS_OPMODE_INF                  61215
#define IDS_OPMODE_ADHOC                61216
#define IDS_OPMODE_REP                  61217
#define IDS_WMODE_B                     61218
#define IDS_WMODE_G                     61219
#define IDS_WMODE_SUPERG                61220
#define IDS_AUTH_DISABLE                61221
#define IDS_DISABLED                    61221
#define IDS_AUTH_WEP64                  61222
#define IDS_AUTH_WEP128                 61223
#define IDS_AUTH_WEP152                 61224
#define IDS_AUTH_WPA_PSK                61225
#define IDS_AUTH_WPA                    61226
#define IDS_CHANNEL_AUTO                61227
#define IDS_ANY_SSID                    61228
#define IDS_ENCRYPTION_TKIP             61229
#define IDS_ENCRYPTION_AES              61230
#define IDS_OPEN_SYSTEM                 61231
#define IDS_ENCRYPTION                  61232
#define IDS_AUTHENTIACTION              61233
#define IDS_SECURITY_WPA_PSK            61234
#define IDS_SECURITY                    61235
#define IDS_SHARED_KEY                  61236
#define IDS_WIZARD_TITLE                61237
#define IDS_ERR_IPFIELD1                61238
#define IDS_ERR_IPFIELD4_ZERO           61239
#define IDS_ERR_IPFIELD4_FILL           61240
#define IDS_ERROR_MASK                  61241
#define IDS_AUTO                        61242
#define IDS_SECURITY_WPA                61243
#define IDS_TEXT_KEY_WPA                61244
#define IDS_TEXT_KEY_WPA_Radius         61245
#define IDS_TEXT_KEY_WPA_IP             61246
#define IDS_TEXT_KEY_WEP_INPUT          61247
#define IDS_WMODE_STATICG               61248

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        258
#define _APS_NEXT_COMMAND_VALUE         32783
#define _APS_NEXT_CONTROL_VALUE         1171
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
