#!/bin/sh /etc/rc.common
START=99
BUT_GPIO_DIR="/tmp/but_gpio"
BUT_GPIO_DIR_1="/tmp/but_gpio/1"
BUT_GPIO_DIR_2="/tmp/but_gpio/2"

log_msg="reset_button"

boot() {
	start
}

start() {
	mknod /dev/gpio c 252 0
	mkdir "${BUT_GPIO_DIR}" 
	mkdir "${BUT_GPIO_DIR_1}" 
	mkdir "${BUT_GPIO_DIR_2}"
	touch "${BUT_GPIO_DIR_1}/14"
	touch "${BUT_GPIO_DIR_2}/14"
	reset_button &
	
}

stop() {
	#rm -rf "${BUT_GPIO_DIR}" >/dev/null 2>/dev/null
	killall reset_button
}
